export * from './components/LandingPage';
export * from './components/PrivacyPolicy';
export * from './components/Terms';
export * from './components/BookDemo';
export * from './components/SolutionsPage';
export * from './components/IndustriesPage';
export * from './components/AboutPage';
export * from './components/MyQCareProductPage';
export * from './components/ProductsPage';
