export const countryCodes = [
  { code: "+93", country: "Afghanistan (AF)" },
  { code: "+355", country: "Albania (AL)" },
  { code: "+213", country: "Algeria (DZ)" },
  { code: "+376", country: "Andorra (AD)" },
  { code: "+244", country: "Angola (AO)" },
  { code: "+54", country: "Argentina (AR)" },
  { code: "+374", country: "Armenia (AM)" },
  { code: "+61", country: "Australia (AU)" },
  { code: "+43", country: "Austria (AT)" },
  { code: "+994", country: "Azerbaijan (AZ)" },
  { code: "+973", country: "Bahrain (BH)" },
  { code: "+880", country: "Bangladesh (BD)" },
  { code: "+375", country: "Belarus (BY)" },
  { code: "+32", country: "Belgium (BE)" },
  { code: "+501", country: "Belize (BZ)" },
  { code: "+229", country: "Benin (BJ)" },
  { code: "+975", country: "Bhutan (BT)" },
  { code: "+591", country: "Bolivia (BO)" },
  { code: "+387", country: "Bosnia and Herzegovina (BA)" },
  { code: "+267", country: "Botswana (BW)" },
  { code: "+55", country: "Brazil (BR)" },
  { code: "+673", country: "Brunei (BN)" },
  { code: "+359", country: "Bulgaria (BG)" },
  { code: "+226", country: "Burkina Faso (BF)" },
  { code: "+257", country: "Burundi (BI)" },
  { code: "+855", country: "Cambodia (KH)" },
  { code: "+237", country: "Cameroon (CM)" },
  { code: "+1", country: "Canada (CA)" },
  { code: "+238", country: "Cape Verde (CV)" },
  { code: "+236", country: "Central African Republic (CF)" },
  { code: "+235", country: "Chad (TD)" },
  { code: "+56", country: "Chile (CL)" },
  { code: "+86", country: "China (CN)" },
  { code: "+57", country: "Colombia (CO)" },
  { code: "+269", country: "Comoros (KM)" },
  { code: "+242", country: "Congo (CG)" },
  { code: "+243", country: "Congo, Democratic Republic of the (CD)" },
  { code: "+506", country: "Costa Rica (CR)" },
  { code: "+385", country: "Croatia (HR)" },
  { code: "+53", country: "Cuba (CU)" },
  { code: "+357", country: "Cyprus (CY)" },
  { code: "+420", country: "Czech Republic (CZ)" },
  { code: "+45", country: "Denmark (DK)" },
  { code: "+253", country: "Djibouti (DJ)" },
  { code: "+1", country: "Dominican Republic (DO)" },
  { code: "+593", country: "Ecuador (EC)" },
  { code: "+20", country: "Egypt (EG)" },
  { code: "+503", country: "El Salvador (SV)" },
  { code: "+240", country: "Equatorial Guinea (GQ)" },
  { code: "+291", country: "Eritrea (ER)" },
  { code: "+372", country: "Estonia (EE)" },
  { code: "+251", country: "Ethiopia (ET)" },
  { code: "+679", country: "Fiji (FJ)" },
  { code: "+358", country: "Finland (FI)" },
  { code: "+33", country: "France (FR)" },
  { code: "+241", country: "Gabon (GA)" },
  { code: "+220", country: "Gambia (GM)" },
  { code: "+995", country: "Georgia (GE)" },
  { code: "+49", country: "Germany (DE)" },
  { code: "+233", country: "Ghana (GH)" },
  { code: "+30", country: "Greece (GR)" },
  { code: "+502", country: "Guatemala (GT)" },
  { code: "+224", country: "Guinea (GN)" },
  { code: "+245", country: "Guinea-Bissau (GW)" },
  { code: "+592", country: "Guyana (GY)" },
  { code: "+509", country: "Haiti (HT)" },
  { code: "+504", country: "Honduras (HN)" },
  { code: "+36", country: "Hungary (HU)" },
  { code: "+354", country: "Iceland (IS)" },
  { code: "+91", country: "India (IN)" },
  { code: "+62", country: "Indonesia (ID)" },
  { code: "+98", country: "Iran (IR)" },
  { code: "+964", country: "Iraq (IQ)" },
  { code: "+353", country: "Ireland (IE)" },
  { code: "+972", country: "Israel (IL)" },
  { code: "+39", country: "Italy (IT)" },
  { code: "+1", country: "Jamaica (JM)" },
  { code: "+81", country: "Japan (JP)" },
  { code: "+962", country: "Jordan (JO)" },
  { code: "+7", country: "Kazakhstan (KZ)" },
  { code: "+254", country: "Kenya (KE)" },
  { code: "+686", country: "Kiribati (KI)" },
  { code: "+965", country: "Kuwait (KW)" },
  { code: "+996", country: "Kyrgyzstan (KG)" },
  { code: "+856", country: "Laos (LA)" },
  { code: "+371", country: "Latvia (LV)" },
  { code: "+961", country: "Lebanon (LB)" },
  { code: "+266", country: "Lesotho (LS)" },
  { code: "+231", country: "Liberia (LR)" },
  { code: "+218", country: "Libya (LY)" },
  { code: "+423", country: "Liechtenstein (LI)" },
  { code: "+370", country: "Lithuania (LT)" },
  { code: "+352", country: "Luxembourg (LU)" },
  { code: "+261", country: "Madagascar (MG)" },
  { code: "+265", country: "Malawi (MW)" },
  { code: "+60", country: "Malaysia (MY)" },
  { code: "+960", country: "Maldives (MV)" },
  { code: "+223", country: "Mali (ML)" },
  { code: "+356", country: "Malta (MT)" },
  { code: "+222", country: "Mauritania (MR)" },
  { code: "+230", country: "Mauritius (MU)" },
  { code: "+52", country: "Mexico (MX)" },
  { code: "+373", country: "Moldova (MD)" },
  { code: "+377", country: "Monaco (MC)" },
  { code: "+976", country: "Mongolia (MN)" },
  { code: "+382", country: "Montenegro (ME)" },
  { code: "+212", country: "Morocco (MA)" },
  { code: "+258", country: "Mozambique (MZ)" },
  { code: "+95", country: "Myanmar (MM)" },
  { code: "+264", country: "Namibia (NA)" },
  { code: "+674", country: "Nauru (NR)" },
  { code: "+977", country: "Nepal (NP)" },
  { code: "+31", country: "Netherlands (NL)" },
  { code: "+64", country: "New Zealand (NZ)" },
  { code: "+505", country: "Nicaragua (NI)" },
  { code: "+227", country: "Niger (NE)" },
  { code: "+234", country: "Nigeria (NG)" },
  { code: "+850", country: "North Korea (KP)" },
  { code: "+47", country: "Norway (NO)" },
  { code: "+968", country: "Oman (OM)" },
  { code: "+92", country: "Pakistan (PK)" },
  { code: "+680", country: "Palau (PW)" },
  { code: "+970", country: "Palestine (PS)" },
  { code: "+507", country: "Panama (PA)" },
  { code: "+675", country: "Papua New Guinea (PG)" },
  { code: "+595", country: "Paraguay (PY)" },
  { code: "+51", country: "Peru (PE)" },
  { code: "+63", country: "Philippines (PH)" },
  { code: "+48", country: "Poland (PL)" },
  { code: "+351", country: "Portugal (PT)" },
  { code: "+974", country: "Qatar (QA)" },
  { code: "+40", country: "Romania (RO)" },
  { code: "+7", country: "Russia (RU)" },
  { code: "+250", country: "Rwanda (RW)" },
  { code: "+685", country: "Samoa (WS)" },
  { code: "+378", country: "San Marino (SM)" },
  { code: "+966", country: "Saudi Arabia (SA)" },
  { code: "+221", country: "Senegal (SN)" },
  { code: "+381", country: "Serbia (RS)" },
  { code: "+248", country: "Seychelles (SC)" },
  { code: "+232", country: "Sierra Leone (SL)" },
  { code: "+65", country: "Singapore (SG)" },
  { code: "+421", country: "Slovakia (SK)" },
  { code: "+386", country: "Slovenia (SI)" },
  { code: "+252", country: "Somalia (SO)" },
  { code: "+27", country: "South Africa (ZA)" },
  { code: "+82", country: "South Korea (KR)" },
  { code: "+34", country: "Spain (ES)" },
  { code: "+94", country: "Sri Lanka (LK)" },
  { code: "+249", country: "Sudan (SD)" },
  { code: "+597", country: "Suriname (SR)" },
  { code: "+268", country: "Swaziland (SZ)" },
  { code: "+46", country: "Sweden (SE)" },
  { code: "+41", country: "Switzerland (CH)" },
  { code: "+963", country: "Syria (SY)" },
  { code: "+886", country: "Taiwan (TW)" },
  { code: "+992", country: "Tajikistan (TJ)" },
  { code: "+255", country: "Tanzania (TZ)" },
  { code: "+66", country: "Thailand (TH)" },
  { code: "+228", country: "Togo (TG)" },
  { code: "+676", country: "Tonga (TO)" },
  { code: "+1", country: "Trinidad and Tobago (TT)" },
  { code: "+216", country: "Tunisia (TN)" },
  { code: "+90", country: "Turkey (TR)" },
  { code: "+993", country: "Turkmenistan (TM)" },
  { code: "+256", country: "Uganda (UG)" },
  { code: "+380", country: "Ukraine (UA)" },
  { code: "+971", country: "United Arab Emirates (AE)" },
  { code: "+44", country: "United Kingdom (UK)" },
  { code: "+1", country: "United States (US)" },
  { code: "+598", country: "Uruguay (UY)" },
  { code: "+998", country: "Uzbekistan (UZ)" },
  { code: "+678", country: "Vanuatu (VU)" },
  { code: "+58", country: "Venezuela (VE)" },
  { code: "+84", country: "Vietnam (VN)" },
  { code: "+967", country: "Yemen (YE)" },
  { code: "+260", country: "Zambia (ZM)" },
  { code: "+263", country: "Zimbabwe (ZW)" }
];
