// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubscriptionManager.Infrastructure.Data;

#nullable disable

namespace SubscriptionManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706060537_WebsiteRelationalSchema")]
    partial class WebsiteRelationalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutCta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ButtonText")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("AboutCtas");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleHighlight")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("AboutHeroes");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("AboutMissions");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutValueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId");

                    b.ToTable("AboutValues");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutVision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("AboutVisions");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@antigravity.com",
                            Name = "System Admin",
                            PasswordHash = "$2a$11$z/bW8QS/Yv7SS2yran4T/eh.yL1aNQlK2cfqgaNZ8ha0OE6rkVl5K"
                        });
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppKey")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.BookDemoFaq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId");

                    b.ToTable("BookDemoFaqs");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.BookDemoHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("BookDemoHeroes");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("integer");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingEcosystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LandingEcosystems");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingEngineering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LandingEngineerings");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingFeatureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("FeatureSubtitle")
                        .HasColumnType("text");

                    b.Property<string>("FeatureTitle")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId");

                    b.ToTable("LandingFeatures");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingFinalCta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ButtonText")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LandingFinalCtas");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryCtaText")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryCtaText")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleHighlight")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LandingHeroes");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalPrivacyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LegalPrivacyPolicies");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("PrivacyPolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("TermsOfServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrivacyPolicyId");

                    b.HasIndex("TermsOfServiceId");

                    b.ToTable("LegalSections");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalTermsOfService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("LegalTermsOfServices");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductCustomSolutions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ButtonText")
                        .HasColumnType("text");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("ProductCustomSolutions");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleHighlight")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId")
                        .IsUnique();

                    b.ToTable("ProductHeaders");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteConfigId");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductModules");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductModuleBullet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductModuleId");

                    b.ToTable("ProductModuleBullets");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.WebsiteConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WebsiteConfigs");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutCta", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("AboutCta")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.AboutCta", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutHero", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("AboutHero")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.AboutHero", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutMission", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("AboutMission")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.AboutMission", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutValueItem", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithMany("AboutValues")
                        .HasForeignKey("WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.AboutVision", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("AboutVision")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.AboutVision", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.BookDemoFaq", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithMany("BookDemoFaqs")
                        .HasForeignKey("WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.BookDemoHero", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("BookDemoHero")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.BookDemoHero", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingEcosystem", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LandingEcosystem")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LandingEcosystem", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingEngineering", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LandingEngineering")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LandingEngineering", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingFeatureItem", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithMany("LandingFeatures")
                        .HasForeignKey("WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingFinalCta", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LandingFinalCta")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LandingFinalCta", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LandingHero", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LandingHero")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LandingHero", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalPrivacyPolicy", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LegalPrivacyPolicy")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LegalPrivacyPolicy", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalSection", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.LegalPrivacyPolicy", "PrivacyPolicy")
                        .WithMany("Sections")
                        .HasForeignKey("PrivacyPolicyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SubscriptionManager.Domain.Entities.LegalTermsOfService", "TermsOfService")
                        .WithMany("Sections")
                        .HasForeignKey("TermsOfServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PrivacyPolicy");

                    b.Navigation("TermsOfService");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalTermsOfService", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("LegalTermsOfService")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.LegalTermsOfService", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Plan", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.Application", "Application")
                        .WithMany("Plans")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.Plan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductCustomSolutions", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("ProductCustomSolutions")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.ProductCustomSolutions", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductHeader", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithOne("ProductHeader")
                        .HasForeignKey("SubscriptionManager.Domain.Entities.ProductHeader", "WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductItem", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.WebsiteConfig", "WebsiteConfig")
                        .WithMany("ProductItems")
                        .HasForeignKey("WebsiteConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteConfig");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductModule", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.ProductItem", "ProductItem")
                        .WithMany("Modules")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductModuleBullet", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.ProductModule", "ProductModule")
                        .WithMany("Bullets")
                        .HasForeignKey("ProductModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductModule");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("SubscriptionManager.Domain.Entities.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SubscriptionManager.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubscriptionManager.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Application", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalPrivacyPolicy", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.LegalTermsOfService", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductItem", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.ProductModule", b =>
                {
                    b.Navigation("Bullets");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SubscriptionManager.Domain.Entities.WebsiteConfig", b =>
                {
                    b.Navigation("AboutCta");

                    b.Navigation("AboutHero");

                    b.Navigation("AboutMission");

                    b.Navigation("AboutValues");

                    b.Navigation("AboutVision");

                    b.Navigation("BookDemoFaqs");

                    b.Navigation("BookDemoHero");

                    b.Navigation("LandingEcosystem");

                    b.Navigation("LandingEngineering");

                    b.Navigation("LandingFeatures");

                    b.Navigation("LandingFinalCta");

                    b.Navigation("LandingHero");

                    b.Navigation("LegalPrivacyPolicy");

                    b.Navigation("LegalTermsOfService");

                    b.Navigation("ProductCustomSolutions");

                    b.Navigation("ProductHeader");

                    b.Navigation("ProductItems");
                });
#pragma warning restore 612, 618
        }
    }
}
